// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	operatorv1 "github.com/openshift/api/operator/v1"
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// IngressOperatorSpec is a HyperFleet-owned mirror of hypershiftv1beta1.IngressOperatorSpec.
// Customers may choose how the default ingress controller endpoints are published, but the
// default serving certificate is platform-managed and set by the service.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.IngressOperatorSpec
type IngressOperatorSpec struct {
	// endpointPublishingStrategy controls how the default ingress controller endpoints are published.
	// +hyperfleet:write-mode=mutable
	EndpointPublishingStrategy *operatorv1.EndpointPublishingStrategy `json:"endpointPublishingStrategy,omitempty"`
	// defaultCertificate references the ingress serving certificate secret. Platform-managed:
	// the service sets this to the managed ingress serving cert, so customers cannot set it.
	// +hyperfleet:write-mode=service-set
	DefaultCertificate hypershiftv1beta1.IngressDefaultCertificateReference `json:"defaultCertificate,omitzero"`
}
