// Code generated by conversion-gen. DO NOT EDIT.

package public

// OperatorConfiguration is a HyperFleet-owned mirror of hypershiftv1beta1.OperatorConfiguration
// that exposes a granular, per-field write-mode surface for OCP operator configuration.
// Only the ingress operator is currently exposed; all other operator configuration
// (e.g. clusterVersionOperator, clusterNetworkOperator) remains platform-managed.
// +hyperfleet:upstream-reduced-object=hypershiftv1beta1.OperatorConfiguration
type OperatorConfiguration struct {
	// ingressOperator specifies configuration for the Ingress Operator in the hosted cluster.
	// +hyperfleet:write-mode=service-set
	IngressOperator *IngressOperatorSpec `json:"ingressOperator,omitempty"`
}
