// Code generated by conversion-gen. DO NOT EDIT.

package conversion

import "strings"

// MirrorTypeMapping defines a type that we mirror from HyperShift upstream
// and need automatic conversion logic for
type MirrorTypeMapping struct {
	FieldName          string // Name of the field in the struct (e.g., "Configuration", "AutoNode")
	HyperFleetType     string // Our mirror type (e.g., "v1alpha1.ClusterConfiguration")
	HyperShiftType     string // Upstream HyperShift type (e.g., "v1beta1.ClusterConfiguration")
	ConversionStrategy string // "json-roundtrip" or "field-by-field"
}

// mirrorTypeMappings is the registry of all mirror types requiring conversion
//
// These are types where:
// 1. HyperFleet owns a mirror version (in api/v1alpha1/) to add granular markers
// 2. HyperShift has the upstream version (in hypershift/api/hypershift/v1beta1/)
// 3. Conversion functions need to convert between the two
//
// When a mirror type exists, the conversion generator will:
// - Detect type mismatches during conversion generation
// - Generate conversion helper functions automatically
// - Use helpers in ProjectX/UnprojectX conversion functions
var mirrorTypeMappings = []MirrorTypeMapping{
	// Configuration: HyperFleet owns a mirror type (api/v1alpha1/configuration.go) to enable granular markers
	// on kubelet and machine config fields, while HyperShift has the upstream version in v1beta1
	{
		FieldName:          "Configuration",
		HyperFleetType:     "v1alpha1.ClusterConfiguration",
		HyperShiftType:     "v1beta1.ClusterConfiguration",
		ConversionStrategy: "json-roundtrip",
	},

	// Platform: HyperFleet owns a reduced mirror (api/v1alpha1/cluster_types.go) that exposes only
	// the AWS platform, excluding Azure, GCP, OpenStack, and other non-supported platforms.
	{
		FieldName:          "Platform",
		HyperFleetType:     "v1alpha1.PlatformSpec",
		HyperShiftType:     "v1beta1.PlatformSpec",
		ConversionStrategy: "json-roundtrip",
	},

	// NodePool Platform: same as above for node pool platform configuration.
	{
		FieldName:          "Platform",
		HyperFleetType:     "v1alpha1.NodePoolPlatform",
		HyperShiftType:     "v1beta1.NodePoolPlatform",
		ConversionStrategy: "json-roundtrip",
	},

	// OperatorConfiguration: HyperFleet owns a reduced mirror (api/v1alpha1/configuration.go)
	// that exposes only the ingress operator, with granular markers so that
	// endpointPublishingStrategy stays customer-mutable while defaultCertificate is
	// platform-managed (service-set). The nested IngressOperatorSpec is handled by the
	// json-roundtrip strategy, so it needs no separate mapping.
	{
		FieldName:          "OperatorConfiguration",
		HyperFleetType:     "v1alpha1.OperatorConfiguration",
		HyperShiftType:     "v1beta1.OperatorConfiguration",
		ConversionStrategy: "json-roundtrip",
	},

	// Add more mirror types here as needed when types diverge between CRD and REST
	// Example:
	// {
	//     FieldName:          "Kubelet",
	//     HyperFleetType:     "v1alpha1.KubeletConfig",
	//     HyperShiftType:     "v1beta1.KubeletConfig",
	//     ConversionStrategy: "json-roundtrip",
	// },
}

// GetMirrorMapping returns the mirror type mapping for a given field name.
// Returns nil if the field is not a mirror type.
func GetMirrorMapping(fieldName string) *MirrorTypeMapping {
	for i := range mirrorTypeMappings {
		if mirrorTypeMappings[i].FieldName == fieldName {
			return &mirrorTypeMappings[i]
		}
	}
	return nil
}

// GetMirrorMappingByHyperShiftType returns the mirror mapping whose upstream
// HyperShift type matches hsTypeName (the base name without a package prefix,
// e.g. "PlatformSpec"). This is used to disambiguate when the same field name
// appears in multiple passthrough types with different HyperShift base types.
func GetMirrorMappingByHyperShiftType(hsTypeName string) *MirrorTypeMapping {
	for i := range mirrorTypeMappings {
		// HyperShiftType is "v1beta1.Foo" — compare just the base name.
		parts := strings.SplitN(mirrorTypeMappings[i].HyperShiftType, ".", 2)
		baseName := parts[len(parts)-1]
		if baseName == hsTypeName {
			return &mirrorTypeMappings[i]
		}
	}
	return nil
}

// LocalTypeName returns the base (unqualified) Go type name from HyperFleetType.
// e.g. "v1alpha1.PlatformSpec" → "PlatformSpec".
func (m *MirrorTypeMapping) LocalTypeName() string {
	parts := strings.SplitN(m.HyperFleetType, ".", 2)
	return parts[len(parts)-1]
}

// IsMirrorType returns true if the field name is registered as a mirror type.
func IsMirrorType(fieldName string) bool {
	return GetMirrorMapping(fieldName) != nil
}
